# Walmart sales: cleaning the dataset 

In [1]:
import pandas as pd

## Load the data using pandas

In [2]:
data = pd.read_csv('data/walmart_dataset.csv', parse_dates=['Date'])
data.head()

Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0      1    A  151315 2010-02-05        42.31       2.572        NaN   
1     35    B  103681 2010-02-05        27.19       2.784        NaN   
2     35    B  103681 2010-02-05        27.19       2.784        NaN   
3     35    B  103681 2010-02-05        27.19       2.784        NaN   
4     35    B  103681 2010-02-05        27.19       2.784        NaN   

   MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0        NaN        NaN        NaN        NaN  211.096358         8.106   
1        NaN        NaN        NaN        NaN  135.352461         9.262   
2        NaN        NaN        NaN        NaN  135.352461         9.262   
3        NaN        NaN        NaN        NaN  135.352461         9.262   
4        NaN        NaN        NaN        NaN  135.352461         9.262   

   IsHoliday  Dept  Weekly_Sales  
0      False     1      24924.50  
1      False     3      14612.19  
2      False     4      26323.15  
3      False     5      36414.63  
4      False     6      11437.81

In [3]:
pd.DataFrame(data.dtypes, columns=['Type'])

Type
Store                  int64
Type                  object
Size                   int64
Date          datetime64[ns]
Temperature          float64
Fuel_Price           float64
MarkDown1            float64
MarkDown2            float64
MarkDown3            float64
MarkDown4            float64
MarkDown5            float64
CPI                  float64
Unemployment         float64
IsHoliday               bool
Dept                   int64
Weekly_Sales         float64

Add two new columns containing the number of the week and the year.

In [4]:
data.Date.dt.month

0          2
1          2
2          2
3          2
4          2
          ..
421565    10
421566    10
421567    10
421568    10
421569    10
Name: Date, Length: 421570, dtype: int64

In [5]:
data['Week'] = data.Date.dt.week 
data['Year'] = data.Date.dt.year
data['Month'] = data.Date.dt.month
data.head()

/home/miguel/anaconda3/envs/specialization/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  """Entry point for launching an IPython kernel.


Store Type    Size       Date  Temperature  Fuel_Price  MarkDown1  \
0      1    A  151315 2010-02-05        42.31       2.572        NaN   
1     35    B  103681 2010-02-05        27.19       2.784        NaN   
2     35    B  103681 2010-02-05        27.19       2.784        NaN   
3     35    B  103681 2010-02-05        27.19       2.784        NaN   
4     35    B  103681 2010-02-05        27.19       2.784        NaN   

   MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  \
0        NaN        NaN        NaN        NaN  211.096358         8.106   
1        NaN        NaN        NaN        NaN  135.352461         9.262   
2        NaN        NaN        NaN        NaN  135.352461         9.262   
3        NaN        NaN        NaN        NaN  135.352461         9.262   
4        NaN        NaN        NaN        NaN  135.352461         9.262   

   IsHoliday  Dept  Weekly_Sales  Week  Year  Month  
0      False     1      24924.50     5  2010      2  
1      False     3      14612.19     5  2010      2  
2      False     4      26323.15     5  2010      2  
3      False     5      36414.63     5  2010      2  
4      False     6      11437.81     5  2010      2

### Count the unique values of the columns Store, Type, Department and IsHoliday

Count the unique values of the columns Store, Type, Department and IsHoliday, which are the columns with categorical data. Then obtain the percentage of the values over the total of registers in the dataset.

In [5]:
store_counts = (data['Store']
                .value_counts()
                .sort_index()
                .to_frame(name="Count")
                .reset_index()
                .rename(columns= {'index': 'Store'}))
store_counts['Percent'] = (store_counts['Count'] / store_counts['Count'].sum()) * 100
store_counts

Store  Count   Percent
0       1  10244  2.429964
1       2  10238  2.428541
2       3   9036  2.143416
3       4  10272  2.436606
4       5   8999  2.134640
5       6  10211  2.422136
6       7   9762  2.315630
7       8   9895  2.347178
8       9   8867  2.103328
9      10  10315  2.446806
10     11  10062  2.386792
11     12   9705  2.302109
12     13  10474  2.484522
13     14  10040  2.381574
14     15   9901  2.348602
15     16   9443  2.239960
16     17   9864  2.339825
17     18   9859  2.338639
18     19  10148  2.407192
19     20  10214  2.422848
20     21   9582  2.272932
21     22   9688  2.298076
22     23  10050  2.383946
23     24  10228  2.426169
24     25   9804  2.325592
25     26   9854  2.337453
26     27  10225  2.425457
27     28  10113  2.398890
28     29   9455  2.242807
29     30   7156  1.697464
30     31  10142  2.405769
31     32  10202  2.420001
32     33   6487  1.538772
33     34  10224  2.425220
34     35   9528  2.260123
35     36   6222  1.475911
36     37   7206  1.709325
37     38   7362  1.746329
38     39   9878  2.343146
39     40  10017  2.376118
40     41  10088  2.392960
41     42   6953  1.649311
42     43   6751  1.601395
43     44   7169  1.700548
44     45   9637  2.285979

In [6]:
print("Store with more registers:\n", store_counts.iloc[store_counts['Percent'].idxmax()], "\n")
print("Store with more registers:\n", store_counts.iloc[store_counts['Percent'].idxmin()])

Store with more registers:
 Store         13.000000
Count      10474.000000
Percent        2.484522
Name: 12, dtype: float64 

Store with more registers:
 Store        36.000000
Count      6222.000000
Percent       1.475911
Name: 35, dtype: float64


In [7]:
type_counts = pd.DataFrame(data['Type']
                .value_counts()
                .sort_index()
                .to_frame(name="Count")
                .reset_index()
                .rename(columns= {'index': 'Type'}))
type_counts['Percent'] = (type_counts['Count'] / type_counts['Count'].sum()) * 100
type_counts

Type   Count    Percent
0    A  215478  51.113220
1    B  163495  38.782409
2    C   42597  10.104372

In [14]:
print("Type with more registers:\n", type_counts.iloc[type_counts['Percent'].idxmax()], "\n")
print("Type with more registers:\n", type_counts.iloc[type_counts['Percent'].idxmin()])

Type with more registers:
 Type             A
Count       215478
Percent    51.1132
Name: 0, dtype: object 

Type with more registers:
 Type             C
Count        42597
Percent    10.1044
Name: 2, dtype: object


In [9]:
dept_counts = pd.DataFrame(data['Dept']
                .value_counts()
                .sort_index()
                .to_frame(name="Count")
                .reset_index()
                .rename(columns= {'index': 'Dept'}))
dept_counts['Percent'] = (dept_counts['Count'] / dept_counts['Count'].sum()) * 100
dept_counts

Dept  Count   Percent
0      1   6435  1.526437
1      2   6435  1.526437
2      3   6435  1.526437
3      4   6435  1.526437
4      5   6347  1.505563
..   ...    ...       ...
76    95   6435  1.526437
77    96   4854  1.151410
78    97   6278  1.489195
79    98   5836  1.384349
80    99    862  0.204474

[81 rows x 3 columns]

In [16]:
print("Department with more registers:\n", dept_counts.iloc[dept_counts['Percent'].idxmax()], "\n")
print("Department with more registers:\n", dept_counts.iloc[dept_counts['Percent'].idxmin()])

Department with more registers:
 Dept          1.000000
Count      6435.000000
Percent       1.526437
Name: 0, dtype: float64 

Department with more registers:
 Dept       43.000000
Count      12.000000
Percent     0.002847
Name: 41, dtype: float64


In [11]:
holiday_counts = (data['IsHoliday']
                .value_counts()
                .sort_index()
                .to_frame(name="Count")
                .reset_index()
                .rename(columns= {'index': 'IsHoliday'}))
holiday_counts['Percent'] = (holiday_counts['Count'] / holiday_counts['Count'].sum()) * 100
holiday_counts

IsHoliday   Count    Percent
0      False  391909  92.964158
1       True   29661   7.035842

In [15]:
print("IsHoliday with more registers:\n", holiday_counts.iloc[holiday_counts['Percent'].idxmax()], "\n")
print("IsHoliday with more registers:\n", holiday_counts.iloc[holiday_counts['Percent'].idxmin()])

IsHoliday with more registers:
 IsHoliday      False
Count         391909
Percent      92.9642
Name: 0, dtype: object 

IsHoliday with more registers:
 IsHoliday       True
Count          29661
Percent      7.03584
Name: 1, dtype: object


### Count the missing values in the markdown columns

Count the quantity of missing values from the markdown columns and their percentage over the total of registers. As more of the 60% of the data from all markdown columns are missing, this columns can be discarded as they won't be useful.

In [13]:
cols = (data.isnull().sum(axis=0)/len(data)).sort_values(ascending=False).index

null_count = data.isnull().sum(axis=0)
null_percent = null_count/len(data) * 100

null_data = pd.concat([null_count, null_percent], axis=1)
null_data = null_data.rename(columns={0: 'Null count', 1: 'Null percent'})
null_data = null_data[null_data['Null count']!=0]
null_data

Null count  Null percent
MarkDown1      270889     64.257181
MarkDown2      310322     73.611025
MarkDown3      284479     67.480845
MarkDown4      286603     67.984676
MarkDown5      270138     64.079038

##

In [14]:
import seaborn as sns

Hacemos drop de columnas con valores NaN

In [33]:
new_data = data.dropna(axis=1)
new_data.columns

Index(['Store', 'Type', 'Size', 'Date', 'Temperature', 'Fuel_Price', 'CPI',
       'Unemployment', 'IsHoliday', 'Dept', 'Weekly_Sales', 'Week', 'Year',
       'Month'],
      dtype='object')

Tambien de la columna fecha pues ya tenemos mes,año,semana en columnas individuales

In [34]:
new_data.drop('Date',axis=1, inplace=True)

/home/miguel/anaconda3/envs/specialization/lib/python3.7/site-packages/pandas/core/frame.py:4167: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Transformamos la columna IsHoliday a valores numericos respectivos.

In [35]:
new_data['IsHoliday'] = new_data['IsHoliday'].apply(lambda x: 1 if x == True else 0)

/home/miguel/anaconda3/envs/specialization/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [36]:
new_data['IsHoliday'].unique()

array([0, 1])

Validamos la consistencia de los datos.
Es sabido que las ventas son positivas. 
La temperatura puede ser positiva y negativa

In [37]:
new_data.describe()

Store           Size    Temperature     Fuel_Price  \
count  421570.000000  421570.000000  421570.000000  421570.000000   
mean       22.200546  136727.915739      60.090059       3.361027   
std        12.785297   60980.583328      18.447931       0.458515   
min         1.000000   34875.000000      -2.060000       2.472000   
25%        11.000000   93638.000000      46.680000       2.933000   
50%        22.000000  140167.000000      62.090000       3.452000   
75%        33.000000  202505.000000      74.280000       3.738000   
max        45.000000  219622.000000     100.140000       4.468000   

                 CPI   Unemployment      IsHoliday           Dept  \
count  421570.000000  421570.000000  421570.000000  421570.000000   
mean      171.201947       7.960289       0.070358      44.260317   
std        39.159276       1.863296       0.255750      30.492054   
min       126.064000       3.879000       0.000000       1.000000   
25%       132.022667       6.891000       0.000000      18.000000   
50%       182.318780       7.866000       0.000000      37.000000   
75%       212.416993       8.572000       0.000000      74.000000   
max       227.232807      14.313000       1.000000      99.000000   

        Weekly_Sales           Week           Year          Month  
count  421570.000000  421570.000000  421570.000000  421570.000000  
mean    15981.258123      25.826762    2010.968591       6.449510  
std     22711.183519      14.151887       0.796876       3.243217  
min     -4988.940000       1.000000    2010.000000       1.000000  
25%      2079.650000      14.000000    2010.000000       4.000000  
50%      7612.030000      26.000000    2011.000000       6.000000  
75%     20205.852500      38.000000    2012.000000       9.000000  
max    693099.360000      52.000000    2012.000000      12.000000

In [39]:
print('Total semanas con registros negativos')
new_data.loc[new_data.Weekly_Sales<0].shape

Total semanas con registros negativos


(1285, 13)

In [40]:
new_data = new_data.loc[new_data.Weekly_Sales>0].reset_index(drop=True)

Realizamos onehot encoding al tipo de tienda, ya que no existe una jerarquia pre establecida

In [62]:
new_data = pd.get_dummies(new_data)

In [63]:
new_data.columns

Index(['Store', 'Size', 'Temperature', 'Fuel_Price', 'CPI', 'Unemployment',
       'IsHoliday', 'Dept', 'Weekly_Sales', 'Week', 'Year', 'Month', 'Type_A',
       'Type_B', 'Type_C'],
      dtype='object')

In [ ]:
Separamos los datos en train y test, tambien el train en datos de de cross validacion

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import (LinearRegression, LogisticRegression, ridge_regression, 
Lasso, SGDRegressor, Ridge)

y = new_data['Weekly_Sales']
X = new_data.drop(['Weekly_Sales'], axis=1) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # Train:Test = 70:30 splitting.
#X_train, X_cv, y_train, y_cv = train_test_split(X_train, y_train, test_size=0.3) #Train:CV = 70:30 splitting.

In [65]:
# Dimensiones finales de los datos de prueba
print('Train:', X_train.shape, y_train.shape)
#print('CV:', X_cv.shape, y_cv.shape)
print('Test', X_test.shape, y_test.shape)

Train: (294148, 14) (294148,)
Test (126064, 14) (126064,)


In [66]:
X_train.head(2)

Store    Size  Temperature  Fuel_Price         CPI  Unemployment  \
122673      4  205863        48.08       2.752  126.669267         7.127   
158777     35  103681        39.32       3.245  137.251185         8.549   

        IsHoliday  Dept  Week  Year  Month  Type_A  Type_B  Type_C  
122673          1    26    47  2010     11       1       0       0  
158777          0     9     7  2011      2       0       1       0

Utilizamos lasso para validar caracteristicas mas importantes

In [68]:
alpha_grid = {'alpha' : [0.000001,0.00001,0.0001,0.001,0.01,0.1,1,10,20,50,100,200,500,1000]}

In [75]:
from sklearn.model_selection import GridSearchCV
grid_search = GridSearchCV(Lasso(max_iter=100000), alpha_grid, cv=5)

In [76]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=Lasso(max_iter=100000),
             param_grid={'alpha': [1e-06, 1e-05, 0.0001, 0.001, 0.01, 0.1, 1,
                                   10, 20, 50, 100, 200, 500, 1000]})

In [77]:
print("Test set score: {:.2f}".format(grid_search.score(X_test, y_test)))
print("Best parameters: {}".format(grid_search.best_params_))
print("Best cross-validation score: {:.2f}".format(grid_search.best_score_))
print("Best estimator:\n{}".format(grid_search.best_estimator_))

Test set score: 0.09
Best parameters: {'alpha': 0.1}
Best cross-validation score: 0.09
Best estimator:
Lasso(alpha=0.1, max_iter=100000)


In [80]:
lasso = Lasso(0.1).fit(X_train, y_train)
lasso.coef_

/home/miguel/anaconda3/envs/specialization/lib/python3.7/site-packages/sklearn/linear_model/_coordinate_descent.py:531: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 27147329763109.492, tolerance: 15176913106.660908
  positive)


array([-1.43642103e+02,  9.91904479e-02,  3.02314316e+00,  2.48572242e+02,
       -2.46157052e+01, -2.50832501e+02,  8.50214175e+02,  1.11136953e+02,
       -1.25049950e+02, -2.66553712e+02,  7.18350129e+02, -1.26581372e+03,
       -1.58621477e+03,  4.54239847e+03])

In [81]:
lasso.coef_

array([-1.43642103e+02,  9.91904479e-02,  3.02314316e+00,  2.48572242e+02,
       -2.46157052e+01, -2.50832501e+02,  8.50214175e+02,  1.11136953e+02,
       -1.25049950e+02, -2.66553712e+02,  7.18350129e+02, -1.26581372e+03,
       -1.58621477e+03,  4.54239847e+03])

In [82]:
lasso.coef_ != 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

Considerando los resultados, ninguno de los parametros es irrelevante por ende no se eliminan

In [ ]:
# Define empty train and cv error list and list of hyper parameter values.
error_cv_lasso = []
error_train_lasso = []


"""Calculating train and cv errors for alpha values."""



lasso = Lasso().fit(X_train, y_train)
print("Training set score: {:.2f}".format(lasso.score(X_train, y_train)))
print("Test set score: {:.2f}".format(lasso.score(X_test, y_test)))
print("Number of features used: {}".format(np.sum(lasso.coef_ != 0)))


for i in alpha: # Loop over alpha
    lasso = Lasso(alpha=i) # Apply Lasso Regresor.
    lasso.fit(X_train, y_train) # Fit the model.
    y_pred_cv_lasso = lasso.predict(X_cv) # Predict CV data.
    y_pred_train_lasso = lasso.predict(X_train) # Predict Train data.
    error_cv_lasso.append(wmae_cv(y_cv, y_pred_cv_lasso)) # Get CV error.
    error_train_lasso.append(wmae_train(y_train, y_pred_train_lasso)) # Get Train error.

In [ ]:
columns = ['Store', 'Type', 'Size','Temperature', 'Fuel_Price', 
           'CPI','Unemployment', 'IsHoliday', 'Dept',
          'Weekly_Sales']